# -*- coding: utf-8 -*-
"""Prompt 库：核心写作方法论（情绪套路 + 细纲契约）与摘要链提示词"""
from .planning import (
    CORE_SETTING_PROMPT,
    VOLUME_OUTLINE_PROMPT,
    CHAPTER_OUTLINE_PROMPT,
    IDEA_EXPAND_PROMPT,
)
from .writing import (
    PROSE_WRITING_PROMPT,
    ENRICH_PROMPT,
    DESLOP_REWRITE_PROMPT,
)
from .memory import (
    TRACKING_UPDATE_PROMPT,
    CHAPTER_SUMMARY_PROMPT,
    GLOBAL_SUMMARY_PROMPT,
)
from .review import (
    REVIEW_PROMPT,
    REVIEW_FIX_PROMPT,
)
from .co_writing import (
    CO_ROLES,
    CO_DIALOGUE_PROMPT,
    CO_SUMMARIZE_PROMPT,
    CO_PRODUCT_STRUCTURES,
    HANDOFF_MARKER,
    unit_text,
    CO_UNIT_OUTLINE_PROMPT,
    CO_OUTLINE_REVIEW_PROMPT,
    CO_READBACK_PROMPT,
    CO_SUPERVISOR_PROMPT,
)

__all__ = [
    "CORE_SETTING_PROMPT", "VOLUME_OUTLINE_PROMPT", "CHAPTER_OUTLINE_PROMPT",
    "IDEA_EXPAND_PROMPT",
    "PROSE_WRITING_PROMPT", "ENRICH_PROMPT", "DESLOP_REWRITE_PROMPT",
    "TRACKING_UPDATE_PROMPT", "CHAPTER_SUMMARY_PROMPT", "GLOBAL_SUMMARY_PROMPT",
    "REVIEW_PROMPT", "REVIEW_FIX_PROMPT",
    "CO_ROLES", "CO_DIALOGUE_PROMPT", "CO_SUMMARIZE_PROMPT",
    "CO_PRODUCT_STRUCTURES", "HANDOFF_MARKER",
    "unit_text", "CO_UNIT_OUTLINE_PROMPT", "CO_OUTLINE_REVIEW_PROMPT",
    "CO_READBACK_PROMPT", "CO_SUPERVISOR_PROMPT",
]
